version: '3.9'
services:
  docuseal:
    container_name: docuseal
    environment:
      - TZ=Europe/Paris
    image: docuseal/docuseal:latest
    hostname: docuseal
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - ../data/docuseal:/data

networks:
  containers:
    external: true