http:
    routers:
        phpmyadmin-router:
            rule: "Host(`phpmyadmin.app.home`)"
            middlewares: "phpmyadmin-sablier@file"
            service: "phpmyadmin-service"
            tls: "true"
        portainer-router:
            rule: "Host(`portainer.app.home`)"
            middlewares: "portainer-sablier@file"
            service: "portainer-service"
            tls: "true"
        homarr-router:
            rule: "Host(`dashboard.app.home`)"
            middlewares: "homarr-sablier@file"
            service: "homarr-service"
            tls: "true"
