http:
    middlewares:
        docuseal-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: DocuSeal
                        refreshFrequency: 2s
                        showDetails: false
                        theme: ghost
                    names: glances
                    sablierUrl: http://sablier:10000
                    sessionDuration: 5m
        glances-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: Glances
                        refreshFrequency: 2s
                        showDetails: false
                        theme: ghost
                    names: glances
                    sablierUrl: http://sablier:10000
                    sessionDuration: 5m
        phpmyadmin-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: phpMyAdmin
                        refreshFrequency: 2s
                        showDetails: false
                        theme: ghost
                    names: phpmyadmin
                    sablierUrl: http://sablier:10000
                    sessionDuration: 5m
        portainer-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: Portainer
                        refreshFrequency: 2s
                        showDetails: false
                        theme: ghost
                    names: portainer
                    sablierUrl: http://sablier:10000
                    sessionDuration: 5m
        homarr-sablier:
            plugin:
                sablier:
                    dynamic:
                        displayName: Homarr
                        refreshFrequency: 2s
                        showDetails: false
                        theme: ghost
                    names: homarr
                    sablierUrl: http://sablier:10000
                    sessionDuration: 5m
