# https://hub.docker.com/r/vaultwarden/server
version: '3.9'
services:
  vaultwarden:
    container_name: vaultwarden
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Europe/Paris
    hostname: vaultwarden
    image: vaultwarden/server:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden-router.middlewares=${TRAEFIK_MIDDLEWARES:-}
      - traefik.http.routers.vaultwarden-router.rule=${TRAEFIK_RULE:-}
      - traefik.http.routers.vaultwarden-router.tls=true
      - traefik.http.services.vaultwarden-service.loadbalancer.server.port=80
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - ../data/vaultwarden:/data

networks:
  containers:
    external: true
