# https://hub.docker.com/r/vaultwarden/server
version: '3.9'
services:
  vaultwarden:
    container_name: vaultwarden
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - TZ=${TZ:-Europe/Paris}
    hostname: vaultwarden
    image: vaultwarden/server:latest
    networks:
      - containers
    ports:
      - 10002:80
    restart: unless-stopped
    volumes:
      - ../data/vaultwarden:/data

networks:
  containers:
    external: true
