# https://hub.docker.com/r/louislam/uptime-kuma
version: '3.9'
services:
  uptime:
    container_name: uptime
    environment:
      - TZ=${TZ:-Europe/Paris}
    image: louislam/uptime-kuma:latest
    networks:
      - containers
    ports:
    - ${PORT}:3001
    volumes:
      - ../data/uptime:/app/data
    restart: unless-stopped

networks:
  containers:
    external: true
