# https://hub.docker.com/r/containrrr/watchtower
services:
  watchtower:
    container_name: watchtower
    environment:
      - TZ=${TZ:-Europe/Paris}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 7 * * 1-5
    hostname: ${HOSTNAME:-}
    image: containrrr/watchtower:latest
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  containers:
    external: true
