# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
version: '3.9'
services:
  phpmyadmin:
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=${PHPMYADMIN_PMA_HOSTS}
      - PMA_VERBOSES=${PHPMYADMIN_PMA_VERBOSES}
      - HIDE_PHP_VERSION=true
      - TZ=Europe/Paris
    hostname: phpmyadmin
    image: phpmyadmin:latest
    networks:
      - containers
    restart: unless-stopped

networks:
  containers:
    external: true