# https://hub.docker.com/r/cloudflare/cloudflared/
version: '3.9'
services:
  cloudflared:
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=Europe/Paris
    hostname: cloudflared
    networks:
      - containers
    image: cloudflare/cloudflared:latest
    restart: unless-stopped

networks:
  containers:
    external: true