# https://hub.docker.com/r/cloudflare/cloudflared/
services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    hostname: cloudflared
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=${TZ:-Europe/Paris}
    networks:
      - containers
    restart: unless-stopped

networks:
  containers:
    external: true
