# https://hub.docker.com/r/cloudflared/cloudflared/
version: '3.9'
services:
  cloudflared:
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TZ=Europe/Paris
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped