# https://hub.docker.com/_/mariadb
version: '3.9'
services:
  mariadb:
    container_name: mariadb
    environment: 
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=${TZ:-Europe/Paris}
    image: mariadb:latest
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    hostname: mariadb
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - ../data/mariadb:/var/lib/mysql

networks:
  containers:
    external: true
