# https://hub.docker.com/_/mariadb
version: '3.9'
services:
  mariadb:
    container_name: mariadb
    environment: 
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - TZ=Europe/Paris
    image: mariadb:latest
    hostname: mariadb
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - ../data/mariadb:/var/lib/mysql

networks:
  containers:
    external: true
