# https://hub.docker.com/r/portainer/portainer-ce
version: '3.9'
services:
  portainer:
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=${TZ:-Europe/Paris}
    hostname: portainer
    image: portainer/portainer-ce:linux-amd64
    networks:
      - containers
    ports:
      - ${PORT}:9000
    restart: unless-stopped
    volumes:
      - ../data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  containers:
    external: true
