# https://hub.docker.com/r/portainer/portainer-ce
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    hostname: portainer
    environment:
      - TZ=${TZ:-Europe/Paris}
    networks:
      - containers
    restart: unless-stopped
    volumes:
      - ../data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9000:9000"

networks:
  containers:
    external: true